### ISSUE TITLE
404 après le formulaire

### ISSUE THREAD

**Issue by SProvost-BfS** [sagarsys/uhd#1]
Salut, l'application me retourne un 404 après avoir rempli le formulaire avec des infos utilisateurs non existants. En revanche si j'essaie de recommencer après, l'application me retourne que j'ai déjà joué. 

![capture d ecran 2018-11-06 a 10 10 57](https://user-images.githubusercontent.com/44800496/48053976-59156900-e1ac-11e8-9235-476ae38d7316.png)

**Comment by sagarsys** [comment]
Bonjour Simon,

Je suis au courant de ce bug. Je l'ai corrigé sur la dernière version en ligne, https://uhd-quizz-app.herokuapp.com ( lien github du code source : github.com/sagarsys/uhd ).

Tenez moi au courant si ça règle le soucis pour vous.

Content de rejoindre l'équipe,
Cdt,
Sagar.

-------- Original Message --------
Subject: [sagarsys/uhd] 404 après le formulaire (#1)
From: Simon PROVOST
To: sagarsys/uhd
CC: Subscribed


Salut, l'application me retourne un 404 après avoir rempli le formulaire avec des infos utilisateurs non existants. En revanche si j'essaie de recommencer après, l'application me retourne que j'ai déjà joué.

[capture d ecran 2018-11-06 a 10 10 57]<https://user-images.githubusercontent.com/44800496/48053976-59156900-e1ac-11e8-9235-476ae38d7316.png>

**Comment by SProvost-BfS** [comment]
Bonjour Sagar,

Le souci est bien réglé sur la dernière version. J'avais téléchargé l'application depuis un lien que l'on m'a envoyé par mail, d'une ancienne version probablement. 

Bienvenue parmi nous !

Cordialement,
Simon.

**Comment by sagarsys** [comment]
Super, ça fait plaisir de l'entendre, et merci :)

Cdt,
Sagar.
